[project]
name = "srm"
version = "0.1.0"
description = "SRM"
readme = "README.md"
requires-python = ">=3.13, <3.13.6"
dependencies = [
    "boto3>=1.42.22",
    "cf-xarray>=0.10.10",
    "cftime>=1.6.5",
    "click>=8.3.1",
    "cloudpathlib>=0.23.0",
    "dask[complete]>=2025.12.0",
    "distributed>=2025.12.0",
    "gilknocker==0.4.1",
    "icechunk>=1.1.15",
    "jupyter>=1.1.1",
    "netcdf4>=1.7.4",
    "obstore>=0.8.2",
    "pip>=25.3",
    "tabulate>=0.9.0",
    "xarray>=2025.12.0",
    "xclim>=0.59.1",
    "zarr>=3.1.5",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"


[tool.uv.sources]
srm = { workspace = true, editable = true }

[tool.pytest.ini_options]
addopts = "-m 'not slow' -ra"
markers = [
    "slow: marks tests as slow/expensive (run with 'pytest -m slow')",
]

[dependency-groups]
test = [
    "pytest>=9.0.2",
    "pytest-xdist>=3.8.0",
    "ipdb>=0.13.13",
    "pre-commit>=4.5.1"
]

coiled-deploy = [
    "bokeh>=3.8.2",
    "coiled>=1.130.0",
    "ipykernel>=7.1.0",
    "jupyter-server-proxy>=4.4.0",
]

input-data = [
    "virtualizarr>=2.2.1",
]

qa = [
    "arro3-core>=0.6.5",
    "duckdb>=1.4.3",
    "geopandas>=1.1.2",
    "hvplot>=0.12.2",
    "ibicus>=1.2.0",
    "matplotlib>=3.10.8",
    "pyarrow>=22.0.0",
    "rasterio>=1.5.0",
    "rasterix>=0.1a4",
    "seaborn>=0.13.2",
    "sparse>=0.17.0",
]

dev = [
    {include-group = "test"},
    {include-group = "coiled-deploy"},
    {include-group = "qa"},
    {include-group = "input-data"}
]