[project]
name = "srm"
version = "0.1.0"
description = "SRM"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cf-xarray>=0.10.9",
    "cloudpathlib>=0.22.0",
    "coiled>=1.118.3",
    "cubed>=0.22.0",
    "cubed-xarray>=0.0.7",
    "dask[complete]>=2025.7.0",
    "distributed>=2025.7.0",
    "exactextract>=0.2.2",
    "flox>=0.10.6",
    "gcsfs>=2025.7.0",
    "h5netcdf>=1.6.4",
    "icechunk>=1.1.4",
    "intake-esm>=2025.7.9",
    "intake-xarray>=2.0.0",
    "ipython>=9.5.0",
    "jupyter>=1.1.1",
    "jupyter-server-proxy>=4.4.0",
    "netcdf4>=1.7.2",
    "obstore>=0.8.1",
    "pandas>=2.3.2",
    "pooch>=1.8.2",
    "pre-commit>=4.3.0",
    "s3fs>=2025.7.0",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.1",
    "virtualizarr[hdf,icechunk]>=2.1.1",
    "xarray[accel,io]>=2025.8.0",
    "xclim>=0.58.1",
    "zarr>=3.1.2",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "ruff>=0.12.12",
]
geo = [
    "arro3-core>=0.6.2",
    "duckdb>=1.4.0",
    "folium>=0.20.0",
    "geodatasets>=2024.8.0",
    "geopandas>=1.1.1",
    "mapclassify>=2.10.0",
    "pyarrow>=21.0.0",
    "rasterio>=1.4.3",
    "rasterix>=0.1a4",
    "sparse>=0.17.0",
]
plot = [
    "bokeh>=3.8.0",
    "holoviews>=1.21.0",
    "hvplot>=0.12.1",
    "matplotlib>=3.10.6",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
