[project]
name = "srm"
version = "0.1.0"
description = "SRM"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arro3-core>=0.6.1",
    "bokeh>=3.7.3",
    "coiled>=1.118.2",
    "dask>=2025.7.0",
    "distributed>=2025.7.0",
    "gcsfs>=2025.7.0",
    "h5netcdf>=1.6.4",
    "icechunk>=1.1.4",
    "ipython>=9.4.0",
    "jupyter>=1.1.1",
    "jupyter-server-proxy>=4.4.0",
    "matplotlib>=3.10.5",
    "netcdf4>=1.7.2",
    "obstore>=0.8.0",
    "pre-commit>=4.3.0",
    "pyarrow>=21.0.0",
    "s3fs>=2025.7.0",
    "universal-pathlib>=0.2.6",
    "virtualizarr[hdf,icechunk]>=2.1.1",
    "xarray>=2025.8.0",
    "zarr>=3.1.1",
]

