# CESM2-WACCM | SSP245 | rsds | Ensemble member 3

gcm: "CESM2-WACCM"
variable: "rsds"
ensemble_member: 3
scenario: "SSP245"

train_period_start: 1978
train_period_end: 2014
predict_period_start: 2015
predict_period_end: 2100

cache_dir: "s3://carbonplan-scratch/srm/bcsd-cache"
output_dir: "s3://carbonplan-srm/output"
environment: "qa"
version: "v1"
