name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::631969445205:role/github-action-role
          role-session-name: ocr-etl-role-session
          aws-region: us-west-2

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies with uv
        run: uv sync

      ## for when we have tests
      # - name: Run tests
      #   run: uv run pytest