name: pytest (for slow tests)

on:
  pull_request:
    types: [labeled, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write 
  contents: read  

jobs:
  slow-test:
    # Only run if the 'slow-test' label is present OR if manually triggered via UI
    if: |
      contains(github.event.pull_request.labels.*.name, 'slow-test') ||
      github.event_name == 'workflow_dispatch'
    
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::631969445205:role/github-action-role
          role-session-name: srm-slow-validator-session
          aws-region: us-west-2

      - name: install uv
        uses: astral-sh/setup-uv@v6

      - name: deps
        run: uv sync --only-group dev

      - name: run slow tests
        run: uv run pytest -m slow -v